import { type Employee } from '../types/employee';

export const EMPLOYEES_MOCK: Employee[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'Admin',
    status: 'Active',
    password: '',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'Manager',
    status: 'Active',
    password: '',
  },
  {
    id: '3',
    name: 'Taylor Le',
    email: 'employee3@example.com',
    role: 'Manager',
    status: 'Active',
    password: '',
  },
  {
    id: '4',
    name: 'Jordan Pham',
    email: 'employee4@example.com',
    role: 'Manager',
    status: 'Active',
    password: '',
  },
  {
    id: '5',
    name: 'Casey Hoang',
    email: 'employee5@example.com',
    role: 'Manager',
    status: 'Active',
    password: '',
  },
  {
    id: '6',
    name: 'Morgan Vo',
    email: 'employee6@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '7',
    name: 'Jamie Bui',
    email: 'employee7@example.com',
    role: 'Employee',
    status: 'Inactive',
    password: '',
  },
  {
    id: '8',
    name: 'Riley Dang',
    email: 'employee8@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '9',
    name: 'Cameron Do',
    email: 'employee9@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '10',
    name: 'Avery Ngo',
    email: 'employee10@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '11',
    name: 'Logan Huynh',
    email: 'employee11@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '12',
    name: 'Skyler Phan',
    email: 'employee12@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '13',
    name: 'Reese Vu',
    email: 'employee13@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '14',
    name: 'Parker Dinh',
    email: 'employee14@example.com',
    role: 'Employee',
    status: 'Inactive',
    password: '',
  },
  {
    id: '15',
    name: 'Drew Truong',
    email: 'employee15@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '16',
    name: 'Quinn Cao',
    email: 'employee16@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '17',
    name: 'Harper Luu',
    email: 'employee17@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '18',
    name: 'Rowan Mai',
    email: 'employee18@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '19',
    name: 'Emerson Ly',
    email: 'employee19@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '20',
    name: 'Finley Ton',
    email: 'employee20@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '21',
    name: 'Alex Nguyen',
    email: 'employee21@example.com',
    role: 'Employee',
    status: 'Inactive',
    password: '',
  },
  {
    id: '22',
    name: 'Sam Tran',
    email: 'employee22@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '23',
    name: 'Taylor Le',
    email: 'employee23@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '24',
    name: 'Jordan Pham',
    email: 'employee24@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '25',
    name: 'Casey Hoang',
    email: 'employee25@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '26',
    name: 'Morgan Vo',
    email: 'employee26@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '27',
    name: 'Jamie Bui',
    email: 'employee27@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '28',
    name: 'Riley Dang',
    email: 'employee28@example.com',
    role: 'Employee',
    status: 'Inactive',
    password: '',
  },
  {
    id: '29',
    name: 'Cameron Do',
    email: 'employee29@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '30',
    name: 'Avery Ngo',
    email: 'employee30@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '31',
    name: 'Logan Huynh',
    email: 'employee31@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '32',
    name: 'Skyler Phan',
    email: 'employee32@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '33',
    name: 'Reese Vu',
    email: 'employee33@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '34',
    name: 'Parker Dinh',
    email: 'employee34@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '35',
    name: 'Drew Truong',
    email: 'employee35@example.com',
    role: 'Employee',
    status: 'Inactive',
    password: '',
  },
  {
    id: '36',
    name: 'Quinn Cao',
    email: 'employee36@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '37',
    name: 'Harper Luu',
    email: 'employee37@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '38',
    name: 'Rowan Mai',
    email: 'employee38@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '39',
    name: 'Emerson Ly',
    email: 'employee39@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '40',
    name: 'Finley Ton',
    email: 'employee40@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '41',
    name: 'Alex Nguyen',
    email: 'employee41@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '42',
    name: 'Sam Tran',
    email: 'employee42@example.com',
    role: 'Employee',
    status: 'Inactive',
    password: '',
  },
  {
    id: '43',
    name: 'Taylor Le',
    email: 'employee43@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '44',
    name: 'Jordan Pham',
    email: 'employee44@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '45',
    name: 'Casey Hoang',
    email: 'employee45@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '46',
    name: 'Morgan Vo',
    email: 'employee46@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '47',
    name: 'Jamie Bui',
    email: 'employee47@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '48',
    name: 'Riley Dang',
    email: 'employee48@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  },
  {
    id: '49',
    name: 'Cameron Do',
    email: 'employee49@example.com',
    role: 'Employee',
    status: 'Inactive',
    password: '',
  },
  {
    id: '50',
    name: 'Avery Ngo',
    email: 'employee50@example.com',
    role: 'Employee',
    status: 'Active',
    password: '',
  }
];
